trigger:
  branches:
    include:
      - main
      - feature/*

resources:
  - repo: self


stages:
  - stage: test
    jobs:
    - job: go_tests
      displayName: Lint & Test Go Application
      steps:
       - task: GoTool@0
         displayName: Install Go Binary
         inputs:
           version: $(goVersion)

       - bash: make download
         displayName: Downloads the dependencies

       - bash: make lint
         displayName: Lints all code with golangci-lint

       - bash: make test
         displayName: Runs all tests

    - job: Semgrep
      displayName: Run semgrep security tests
      steps:
      - bash: |
          docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 semgrep-agent \
          --config p/secrets \
          --config p/ci \
          --config p/r2c \
          --config p/r2c-ci \
          --config p/docker \
          --config p/dockerfile \
          --config p/command-injection \
          --config p/security-audit
        displayName: Semgrep

  - stage: build
    dependsOn: test
    displayName: Build image yawol-controller
    jobs:
    - job: build_yawol_controller
      displayName: yawol-controller
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: image
        inputs:
          command: build
          arguments: "--target yawol-controller"
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          #containerRegistry: reg.infra.ske.eu01.stackit.cloud/ske/yawol-controller
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tag') }}:
            tags: $(Build.SourceBranchName)
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads') }}:
            tags: $(Build.BuildNumber)
