trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - feature/*

resources:
  - repo: self

variables:
  - name: goVersion
    value: 1.17

stages:
  - stage: test
    jobs:
    - job: go_tests
      displayName: Lint & Test Go Application
      steps:
       - task: GoTool@0
         displayName: Install Go Binary
         inputs:
           version: $(goVersion)

       - bash: make download
         displayName: Downloads the dependencies

       - bash: make lint
         displayName: Lints all code with golangci-lint

       - bash: make test
         displayName: Runs all tests

  - stage: build
    dependsOn: test
    displayName: Build container image
    jobs:
    - job: build_yawol_controller
      displayName: yawol-controller
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: image
        inputs:
          command: buildAndPush
          arguments: "--target yawol-controller"
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          containerRegistry: ske-reg-yawol
          repository: ske/yawol-controller
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tag') }}:
            tags: $(Build.SourceBranchName)
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads') }}:
            tags: $(Build.BuildNumber)
    - job: build_yawol_cloud_controller
      displayName: yawol-cloud-controller
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: image
          inputs:
            command: buildAndPush
            arguments: "--target yawol-cloud-controller"
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            containerRegistry: ske-reg-yawol
            repository: ske/yawol-cloud-controller
            ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tag') }}:
              tags: $(Build.SourceBranchName)
            ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads') }}:
              tags: $(Build.BuildNumber)

  - stage: packer
    dependsOn: test
    displayName: build yawollet image
    jobs:
    - job: build_packer
      displayName: packer
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: GoTool@0
          displayName: Install Go Binary
          inputs:
            version: $(goVersion)
        - bash: make download
          displayName: Downloads the dependencies
        - bash: make get-envoy
          displayName: Downloads envoy
        - bash: CGO_ENABLED=0 go build -o bin/manager ./cmd/yawollet/main.go
          displayName: build yawollet
