trigger:
  branches:
    include:
      - main
      - feature/*

resources:
  - repo: self


stages:
  - stage: build
    displayName: Build image yawol-controller
    jobs:
      - job: build_yawol_controller
        displayName: yawol-controller
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: image
            inputs:
              command: build
              arguments: "--target yawol-controller"
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              #containerRegistry: reg.infra.ske.eu01.stackit.cloud/ske/yawol-controller
              ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tag') }}:
                tags: $(Build.SourceBranchName)
              ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads') }}:
                tags: $(Build.BuildNumber)
