apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: yawol-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
