# LBM for testing yawollet locally
apiVersion: yawol.stackit.cloud/v1beta1
kind: LoadBalancerMachine
metadata:
  name: loadbalancermachine-sample
  namespace: yawol-test
spec:
  floatingID: none # is not used by yawollet can be set to anything
  infrastructure: # is not used by yawollet can be set to anything
    authSecretRef:
      name: none
      namespace: none
    networkID: none
  loadBalancerRef:
    name: loadbalancer-sample
    namespace: yawol-test
