apiVersion: v1
kind: ServiceAccount
metadata:
  name: lbuser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: lbtest
rules:
  - apiGroups: ["yawol.stackit.cloud"]
    resources: ["loadbalancers"]
    verbs: ["list",  "watch"]
  - apiGroups: ["yawol.stackit.cloud"]
    resources: ["loadbalancers"]
    verbs: ["get"]
    resourceNames:
      - loadbalancer-sample
  - apiGroups: [ "yawol.stackit.cloud" ]
    resources: [ "loadbalancermachines" ]
    verbs: [ "list",  "watch" ]
  - apiGroups: ["yawol.stackit.cloud"]
    resources: ["loadbalancermachines"]
    verbs: ["get", "update", "patch"]
    resourceNames:
      - loadbalancer-sample
  - apiGroups: ["yawol.stackit.cloud"]
    resources: ["loadbalancermachines/status"]
    verbs: ["get", "update", "patch"]
    resourceNames:
      - loadbalancer-sample
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lbtest
  namespace: default
subjects:
  - kind: ServiceAccount
    name: lbuser
    namespace: default
roleRef:
  kind: Role
  name: lbtest
  apiGroup: rbac.authorization.k8s.io