apiVersion: yawol.stackit.cloud/v1beta1
kind: LoadBalancerMachine
metadata:
  name: lbm-1
  namespace: default
spec:
  floatingID: 64e0c0ba-794d-4487-9383-c4c98cb469ed
  infrastructure:
    authSecretRef:
      name: cloud-provider-config
      namespace: default
    flavor:
      flavor_id: osAyv1W3z2TU5D6h
    floatingNetID: floating-net
    image:
      image_id: 61d27f7d-959e-406b-a7a8-e4e05c0ead00
    networkID: a9d32d04-87f1-47ef-8da4-a8fda4353bc1
  loadBalancerRef:
    name: lb1
    namespace: default
  portID: 72cf7a7e-0b35-4cbc-aa20-8c6c1be90713
status:
  metrics:
  - timestamp: "2021-03-16T08:27:40Z"
    type: stealTime
    value: "46145"
  - timestamp: "2021-03-16T08:27:40Z"
    type: memAvailable
    value: "770516"
  - timestamp: "2021-03-16T08:27:40Z"
    type: memFree
    value: "582880"
  - timestamp: "2021-03-16T08:27:40Z"
    type: memTotal
    value: "1013408"
  - timestamp: "2021-03-16T08:27:40Z"
    type: load15
    value: "2.00"
  - timestamp: "2021-03-16T08:27:39Z"
    type: load5
    value: "1.00"
  - timestamp: "2021-03-16T08:27:39Z"
    type: load1
    value: "0.15"
