# Example LBM as created by yawol-controller from LBS (some fields were omitted)
apiVersion: yawol.stackit.cloud/v1beta1
kind: LoadBalancerMachine
metadata:
  labels:
    lbm-template-hash: r2dv4eyyfs25gkj2
    yawol.stackit.cloud/loadbalancer: yyjki53tcryt5pcw
  name: yawol-test--loadbalancer-r2dv4eyyfs25gkj2-1ca82
  namespace: yawol-test
  ownerReferences:
  - apiVersion: yawol.stackit.cloud/v1beta1
    kind: LoadBalancerSet
    name: yawol-test--loadbalancer-r2dv4eyyfs25gkj2
spec:
  floatingID: FIP-ID
  infrastructure:
    authSecretRef:
      name: cloud-provider-config
      namespace: yawol-test
    flavor:
      flavor_id: FLAVOR-ID
    floatingNetID: FLOATINGNET-ID
    image:
      image_id: IMAGE-ID-FOR-YAWOLLET-IMAGE
    networkID: NETWORK-ID
  loadBalancerRef:
    name: yawol-test--loadbalancer
    namespace: yawol-test
status:
  conditions:
  - lastHeartbeatTime: "TIMESTAMP"
    lastTransitionTime: "TIMESTAMP"
    message: envoy snapshot version is up to date
    reason: EnvoySnapshotUpToDate
    status: "True"
    type: EnvoyUpToDate
  - lastHeartbeatTime: "TIMESTAMP"
    lastTransitionTime: "TIMESTAMP"
    message: envoy response with 200
    reason: EnvoyReady
    status: "True"
    type: EnvoyReady
  - lastHeartbeatTime: "TIMESTAMP"
    lastTransitionTime: "TIMESTAMP"
    message: envoy config is already up to date
    reason: EnvoyConfigurationCreated
    status: "True"
    type: ConfigReady
  creationTimestamp: "TIMESTAMP"
  lastOpenstackReconcile: "TIMESTAMP"
  metrics:
  - timestamp: "TIMESTAMP"
    type: load1
    value: "0.01"
  - timestamp: "TIMESTAMP"
    type: load5
    value: "0.02"
  - timestamp: "TIMESTAMP"
    type: load15
    value: "0.00"
  - timestamp: "TIMESTAMP"
    type: memTotal
    value: "1011716"
  - timestamp: "TIMESTAMP"
    type: memFree
    value: "822020"
  - timestamp: "TIMESTAMP"
    type: memAvailable
    value: "935952"
  - timestamp: "TIMESTAMP"
    type: stealTime
    value: "11"
  - timestamp: "TIMESTAMP"
    type: TCP-80-upstream_cx_active
    value: "0"
  - timestamp: "TIMESTAMP"
    type: TCP-80-upstream_cx_connect_fail
    value: "0"
  - timestamp: "TIMESTAMP"
    type: TCP-80-upstream_cx_rx_bytes_total
    value: "853"
  - timestamp: "TIMESTAMP"
    type: TCP-80-upstream_cx_total
    value: "1"
  - timestamp: "TIMESTAMP"
    type: TCP-80-upstream_cx_tx_bytes_total
    value: "41"
  portID: PORT-ID
  roleName: yawol-test/yawol-test--loadbalancer-r2dv4eyyfs25gkj2-1ca82
  serverID: SERVER-ID
  serviceAccountName: yawol-test/yawol-test--loadbalancer-r2dv4eyyfs25gkj2-1ca82
