# Example LBS as created by yawol-controller from LB (some fields were omitted)
apiVersion: yawol.stackit.cloud/v1beta1
kind: LoadBalancerSet
metadata:
  labels:
    lbm-template-hash: r2dv4eyyfs25gkj2
    yawol.stackit.cloud/loadbalancer: yyjki53tcryt5pcw
  name: yawol-test--loadbalancer-r2dv4eyyfs25gkj2
  namespace: yawol-test
  ownerReferences:
  - apiVersion: yawol.stackit.cloud/v1beta1
    kind: LoadBalancer
    name: yawol-test--loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      lbm-template-hash: r2dv4eyyfs25gkj2
      yawol.stackit.cloud/loadbalancer: yyjki53tcryt5pcw
  template:
    lables:
      lbm-template-hash: r2dv4eyyfs25gkj2
      yawol.stackit.cloud/loadbalancer: yyjki53tcryt5pcw
    spec:
      floatingID: FIP-ID
      infrastructure:
        authSecretRef:
          name: cloud-provider-config
          namespace: yawol-test
        flavor:
          flavor_id: FLAVOR-ID
        floatingNetID: FLOATINGNET-ID
        image:
          image_id: IMAGE-ID-FOR-YAWOLLET-IMAGE
        networkID: NETWORK-ID
      loadBalancerRef:
        name: yawol-test--loadbalancer
        namespace: yawol-test
status:
  readyReplicas: 1
  replicas: 1
