apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: yawol-controller
  namespace: {{ .Values.namespace }}
  labels:
    app: kubernetes
    role: yawol-controller
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: yawol-controller
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: kubernetes
        role: yawol-controller
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: yawol-controller
      containers:
        - name: yawol-controller-loadbalancer
          image: {{ index .Values.images "yawol-controller" }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: metrics
          command:
            - /bin/yawol-controller
            - -enable-leader-election
            - -enable-loadbalancer-controller
          {{- if .Values.migrateFromOctavia }}
            - --migrate-from-octavia={{ .Values.migrateFromOctavia }}
          {{- end }}
          {{- if .Values.yawolDebug }}
            - --debug={{ .Values.yawolDebug }}
          {{- end }}
          env:
          {{- if .Values.namespace }}
          - name: CLUSTER_NAMESPACE
            value: {{ .Values.namespace }}
          {{- end }}
        - name: yawol-controller-loadbalancerset
          image: {{ index .Values.images "yawol-controller" }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: metrics
          command:
            - /bin/yawol-controller
            - -enable-leader-election
            - -enable-loadbalancerset-controller
            {{- if .Values.migrateFromOctavia }}
            - --migrate-from-octavia={{ .Values.migrateFromOctavia }}
            {{- end }}
            {{- if .Values.yawolDebug }}
            - --debug={{ .Values.yawolDebug }}
            {{- end }}
          env:
            {{- if .Values.namespace }}
            - name: CLUSTER_NAMESPACE
              value: {{ .Values.namespace }}
            {{- end }}
        - name: yawol-controller-loadbalancermachine
          image: {{ index .Values.images "yawol-controller" }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: metrics
          command:
            - /bin/yawol-controller
            - -enable-leader-election
            - -enable-loadbalancermachine-controller
            {{- if .Values.migrateFromOctavia }}
            - --migrate-from-octavia={{ .Values.migrateFromOctavia }}
            {{- end }}
            {{- if .Values.yawolDebug }}
            - --debug={{ .Values.yawolDebug }}
            {{- end }}
          env:
            {{- if .Values.namespace }}
            - name: CLUSTER_NAMESPACE
              value: {{ .Values.namespace }}
              {{- end }}
            {{- if .Values.yawolAPIHost }}
            - name: API_ENDPOINT
              value: {{ .Values.yawolAPIHost }}
            {{- end }}
      restartPolicy: Always

